### ISSUE TITLE
Please make use of "branch"

### ISSUE THREAD

**Issue by ice1000** [xtlsoft/XPHP#6]
> 请勿直接clone主分支，因为1.0.0版还在开发。 你可以从此处下载XPHP的0.3.0版：https://github.com/xtlsoft/XPHP/releases/

You can create a dev branch alone with the master branch so people will always see the stable version.

**Comment by xtlsoft** [comment]
Thank you.

**Comment by xtlsoft** [comment]
But it's my fault, the version 1.0.x is currently stable.
I will change the Readme.md.

-----
Regards, 
xtlsoft.

Copyright xtlsoft(c) 2016-2018,
